version: '3.4'

services:
  mysql.notification.dev:
    container_name: mysql.notification.dev
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3337:3306"

volumes:
  notification_db:
